version: '2'
services: 
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: system
      MONGO_INITDB_ROOT_PASSWORD: system
    networks:
      - app-network  
    volumes: 
      - mongodbdata:/data/db

  application:
    build:
      context: .
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGODB_DB_NAME: playlist-manager
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USER: system
      MONGODB_PASSWORD: system
      MONGODB_AUTHENTICATION_BASE: admin
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  mongodbdata: 